### ISSUE TITLE
Downloads URLError

### ISSUE THREAD

**Issue by tcassanelli** [Cosmoglobe/Cosmoglobe#14]
Hi,

This is not an issue with respect to the code, which I believe should be working, but the links to download the data seem broken?
I tried to directly get them in this [link](https://www.cosmoglobe.uio.no/products/cosmoglobe-dr1.html), but I still cannot access them.

```python
import cosmoglobe
chain = cosmoglobe.get_test_chain()
```

Then the error:
```python
Traceback (most recent call last):
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/tcassanelli/anaconda3/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/Users/tcassanelli/anaconda3/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/Users/tcassanelli/anaconda3/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tcassanelli/anaconda3/lib/python3.9/site-packages/cosmoglobe/__init__.py", line 37, in get_test_chain
    file = download_file(filename, cache=cache)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1532, in download_file
    raise errors[sources[0]]
  File "/Users/tcassanelli/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1500, in download_file
    f_name = _download_file_from_source(
  File "/Users/tcassanelli/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1284, in _download_file_from_source
    with _try_url_open(
  File "/Users/tcassanelli/anaconda3/lib/python3.9/site-packages/astropy/utils/data.py", line 1202, in _try_url_open
    return urlopener.open(req, timeout=timeout)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/tcassanelli/anaconda3/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```
I am not really familiar with any of these cosmology data products, but it would be awesome I we could get a simple Jupyter showing how to compile the chain files yourself and to not fall into this problems, or equivalently make the links available again.
Thanks!

**Comment by MetinSa** [comment]
Hi, apologies for not responding to this Github issue before now. 

The problem seems to be that the server hosting our files had updated their protocol from http to https without my knowledge. The links should be correct now as of https://github.com/Cosmoglobe/Cosmoglobe/commit/20f18cf9be3043c43dd9ecf3a2224e3dd060624d. Make sure to update the package to the newest version.

Thanks highlighting the issue!
